- Jenkinsfile.d/package
- Jenkinsfile.d/release
- PodTemplates.d/package-linux
- PodTemplates.d/release-linux.yaml
* Configure MAVEN_OPTS and container limit to avoid oom killer
* Remove obsolete comments
* Enable window packaging
> Various improvements

- Jenkinsfile.d/release
- profile.d/stable
- profile.d/weekly
- utils/release.sh
* Define Release profile
* Use different branch name variable than the one defined by Jenkins in order to avoid conflicts
* Update mvn cli arguments in order to work with default pom.xml
> Improve mvn release plugin usage

- Jenkinsfile.d/release
- PodTemplates.d/package-linux
- PodTemplates.d/package-windows
- PodTemplates.d/release-linux.yaml
- utils/release.sh
- Fix ssh agent issues when running from a different container than jnlp (by using the jnlp container)
- Run root container as user 1000
> Improve releasing process

- README.adoc
Just a summary of my repositories and review.
https://issues.jenkins-ci.org/browse/INFRA-2348
CC @olblak @MarkEWaite
> [INFRA-2348] - Create a top-level documentation for the Jenkins Core Release Flow

- Jenkinsfile.d/package
- PodTemplates.d/package-windows
* By default package for experimental line
* Increase memory limit for windows pods
> Package by default for experimental line

- utils/release.sh
SIGN_KEYSTORE need to be in the right location
> By default create SIGN_KEYSTORE

- utils/release.sh
should fix transfer progress still showing up
> Pass arguments through to maven release plugin

- utils/release.sh
We would definitely need some bats tests
> Replace AZURE_VAULT_FILE by SIGN_CERTIFICATE variable

- utils/release.sh
> Add missing password

- utils/release.sh
> Drop working directory when we're already there

- utils/release.sh
> Fix function call

- Jenkinsfile.d/package
Counterpart of https://github.com/jenkinsci/packaging/pull/138
Untested
> Publish MSIs from Linux containers

- Jenkinsfile.d/package
the *msi* archive above archives the correct checksum
> Remove unneeded archive

- README.adoc
This pull request is a first attempt to document the release process.
It includes instruction for 
* releasing
* packaging
* manage code signing certificate
Feel free to highlight any missing documentation
> Update README with release, package, certificate information

- Jenkinsfile.d/package
- Jenkinsfile.d/release
- profile.d/weekly
Once this pull request is merged and credentials updated, the release will be done directory to jenkinsci/jenkins on master branch and packages will be pushed to pkg.jenkins.io
Once all credentials are ready to be configured, I'll do one last reset of release.ci.jenkins.io
> Switch to weekly release

- Jenkinsfile.d/core/weekly
cc @olblak @oleg-nenashev @MarkEWaite
> Update weekly release to be on Tuesday

- Jenkinsfile.d/core/package
https://hub.docker.com/r/jenkins4eval/jnlp-agent-vstools-managed
> Remove windows until container is updated

- Jenkinsfile.d/core/package
- PodTemplates.d/package-windows
> Reenable windows packaging with official dotnet images

- Jenkinsfile.d/core/package
> Enable core packaging for security and stable releases

- profile.d/components/remoting
- profile.d/experimental
- profile.d/security
- profile.d/stable
- profile.d/weekly
> Fix git config

- Jenkinsfile.d/components/remoting
- Jenkinsfile.d/core/package
- Jenkinsfile.d/core/release
Solve `WorkflowScript: 60: Expected one of "steps", "stages", or "parallel" for stage "Validate" @ line 60, column 7.
`
> Add steps to validation stage

- utils/release.sh
Same than https://github.com/jenkins-infra/release/pull/78
> [MRELEASE-1048] remove mvn -ntp parameter [2/2]

- PodTemplates.d/release-linux.yaml
Reverts jenkins-infra/release#91
It didn't help
> Revert "Try old version of maven to fix signing issue"

- Jenkinsfile.d/core/package
- utils/release.sh
This PR requires FASTLY_API_TOKEN to be available on release.ci, pr coming
> Invalidate fastly cache during packaging process

- README.adoc
- profile.d/security
- utils/release.sh
Reusing the branch, is that OK?
> Configuration for 2.235.5

- utils/release.sh
I think @jtnord explained that to me a while back?
https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#deployAtEnd
Untested. Might need to be put in `-Darguments`, unsure.
> Set deployAtEnd from maven-deploy-plugin

- Jenkinsfile.d/core/package
This needs to have https://github.com/jenkinsci/packaging/pull/125 merged before this is merged.
> Hacktoberfest - Update to use master branch

- profile.d/stable
See https://github.com/jenkinsci/jenkins/pull/5024 for the changelog.
> Build and package 2.249.3

- PodTemplates.d/package-linux
- PodTemplates.d/package-windows
> Use emptyDir instead

- Jenkinsfile.d/core/package
- Jenkinsfile.d/core/release
> Add stable-rc profile to generic Jenkinsfile

- Jenkinsfile.d/core/release
> Add missing comma

- Jenkinsfile.d/core/stable-rc
> Update stable-rc pod label

- profile.d/stable
(noticed when diffing branches)
> Fix maven repo name on master branch for LTS

- utils/release.bash
For now I am going to disable this.
> Don't guess parameters based on git branch

- profile.d/stable
I should have followed the order of items in the [2.263.3 release checklist](https://github.com/jenkins-infra/release/issues/131) and done this before starting the build
> Package Jenkins 2.263.3

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Discovered during 2.263.3 release process.
> Add Docker image & ci.jenkins.io update tasks

- profile.d/stable
> Prep for 2.277.2 release

- profile.d/security
Really unsure whether this is correct, the docs do not match file contents 😞
> Prepare for April 7 security update (weekly)

- profile.d/stable
See https://github.com/jenkins-infra/release/issues/148
> Prep for 2.277.3 release

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
- Name the scripts in the checklist hyperlinks
- Use stable-2.277 as example branch
> Name scripts in the checklist

- PodTemplates.d/package-windows
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
(cherry picked from commit 3074796e44b486dcf6d6358701b642fe5958fdf2) 
Twin PR of #164 but for the weekly (e.g. on master branch)
> fix: remove volumeMounts for windows packaging

- profile.d/security
About the branches: I created the origin branch from `stable-2.289` and applied these changes to my fork.
> Prepare for 2.289.2 security update

- profile.d/security
> Prepare for 2.300 security update

- profile.d/stable
@MarkEWaite @timja @daniel-beck (I cannot include reviewers, neither merge)
> Prep for 2.303.2 release

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
#193 included a phrasing that was unclear.  Thanks to @daniel-beck for noting that it was unclear.  This tries to improve the clarity
> Better describe lts-candidate issue update process

- Jenkinsfile.d/core/package
- PodTemplates.d/package-linux
Ref. https://github.com/jenkins-infra/jenkins.io/issues/4797
It's a first step
> fix: switch linux packaging to single-container JNLP with dduportal image

- PodTemplates.d/package-linux
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> Bump package image to jenkinsciinfra/packaging:2.0.0

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
fyi @imonteroperez 
based on ping in https://github.com/jenkins-infra/release/issues/209
> Add that changelog is normally docs team

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Minor updates to the release checklist
> Update LTS release checklist

- utils/release.bash
Use rollback instead of rollblack to invoke the rollback shell function
> Call to rollback would fail due to wrong name

- PodTemplates.d/package-linux.yaml
- PodTemplates.d/release-linux.yaml
Fixes https://github.com/jenkins-infra/release/issues/202
(needs to be merged before weekly tomorrow or it will fail)
> Update packaging image

- utils/release.bash
https://github.com/jenkins-infra/docker-packaging/pull/36#issuecomment-1149222550
> Change `generate-resources` to `compile`

- utils/release.bash
https://github.com/jenkins-infra/release/pull/242#issuecomment-1150254796
> Revert generate-resources / compile

- .gitignore
- Jenkinsfile.d/core/package
- Jenkinsfile.d/core/release
- profile.d/stable
Ref. https://github.com/jenkins-infra/release/pull/256
>  Revert Ubuntu 22.04/ JDK8-removal changes for *security* stable 2.346

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
- .github/ISSUE_TEMPLATE/config.yml
Minor modifications using the correct IRC server & channel, default label, my release samples (providing a bit more information about a release than the dreary "hey here is this and that") and updated information in case of security releases.
> docs: Update issue template

- Jenkinsfile.d/core/weekly
Reverts jenkins-infra/release#266
> Revert "Holding weekly"

- PodTemplates.d/package-linux.yaml
- PodTemplates.d/release-linux.yaml
- utils/release.bash
> Merge master branch into stable-2.361.1

- README.adoc
Amends #290. Keeps the documentation up-to-date with the new Maven repository format.
> Update documentation with new Maven repository format

- README.adoc
- utils/release.bash
https://github.com/jenkins-infra/helpdesk/issues/3143#issuecomment-1259692592
(cherry picked from commit 4a61824 / #291 and commit 43a9681 / #292)
> [JENKINS-69666] Core Release: Staging not working anymore

- .github/workflows/updatecli.yaml
> fixup(gha): remove remaining `uses`

- profile.d/stable
1. Update `profile.d/stable` for new point release.
> Init LTS 2.387.2

- README.adoc
Depends on https://github.com/jenkins-infra/docker-openvpn/pull/255
> Update README.adoc with `private.vpn.jenkins.io` mentions

- Jenkinsfile.d/core/package
- Revert "Disable MSI packaging"
> Enable MSI package signing

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Fixes #155. See https://github.com/jenkinsci/acceptance-test-harness/pull/1097#discussion_r1157998618. Would be obviated by https://github.com/jenkinsci/acceptance-test-harness/issues/1098.
> Document ATH in release checklist

- README.adoc
Closes https://github.com/jenkins-infra/helpdesk/issues/3361
Implementation from https://github.com/jenkins-infra/helpdesk/issues/3323#issuecomment-1499361384
> Update the code signing certificate renewal process

- docs/releases.md
Related to https://github.com/jenkinsci/docker/pull/1630
> docs: update Docker image release step

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
- tools/README.md
- tools/init-lts-line
- tools/list-issue-commits
- tools/lts-candidate-stats
Completes https://github.com/jenkins-infra/backend-commit-history-parser/pull/22#issuecomment-1570443424
> Add LTS toolkit

- profile.d/stable
Updated `JENKINS_VERSION` in `profile.d/stable` for new point release.
> Init LTS 2.401.2

- Jenkinsfile.d/core/weekly
Reverts jenkins-infra/release#400
> Revert "Disable weekly build temporarily"

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Oops, forgot that part in https://github.com/jenkins-infra/release/pull/414
> Follow up to #414

- PodTemplates.d/package-linux.yaml
- PodTemplates.d/package-windows.yaml
- PodTemplates.d/release-linux.yaml
THis PR explicitly specify the agent java bin
> fixup of #419

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/updatecli.yaml
- PodTemplates.d/package-linux.yaml
- PodTemplates.d/package-windows.yaml
- PodTemplates.d/release-linux.yaml
- docs/releases.md
This PR backports recents changes in the weekly line to this LTS.
Core of the changes is the [Switch to JDK17 for agent processes](https://github.com/jenkins-infra/helpdesk/issues/3072)
Please merge this PR only when the weekly 2.420 is confirmed built and released
> Cherry pick of recent changes from weekly line for the new LTS 2.414.1

- README.adoc
This note does not look like it should apply to the special config files for security.
> Remove wrong note

- profile.d/stable
Updated JENKINS_VERSION in profile.d/stable.
> Init LTS 2.426.3

- Jenkinsfile.d/core/weekly
Revert https://github.com/jenkins-infra/release/pull/494
> Revert 'Disable weekly build temporarily'

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
We already have tasks around these on our side, but another set of eyes cannot hurt to ensure this isn't being missed.
> Additional tasks around security fixes in 2.xxx.3 releases

- Jenkinsfile.d/core/infra-agents-health
as per https://github.com/jenkins-infra/helpdesk/issues/4042
create a pipeline to check each podtemplate agent health.
tested on release.ci with a single pipeline pointing to my branch.
> chore(release/agent-health): add an infra test pipeline to check agents health

- Jenkinsfile.d/core/infra-agents-health
following #525
update check for windows agent
> chore(infra-agents-health): change test for windows agent as there is no maven

- Jenkinsfile.d/core/infra-agents-health
> chore(infra-agents-health) improve windows checks

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
- tools/init-lts-line
The change proposed automates updating the release profiles in this repository, when creating a new baseline:
> Automate release profile update

- utils/release.bash
Add MAVEN_REPOSITORY_USERNAME and MAVEN_REPOSITORY_PASSWORD comments
> Update comments in release.bash

- Jenkinsfile.d/core/weekly
Reverts jenkins-infra/release#591
Ref. https://github.com/jenkins-infra/helpdesk/issues/4274#issuecomment-2328301727
> Revert "delay weekly"

- Jenkinsfile.d/core/weekly
Reverts jenkins-infra/release#621
> Revert "Temporarily disable weekly build"

- .gitignore
- profile.d/stable
Updated `JENKINS_VERSION` value to `2.479.3` in "profile.d/stable".
> chore(lts): init 2.479.3 lts

- tools/init-lts-line
On MacOS this script does not work because of the two sed commands.
I propose a fix to make this work.
> Fix init lts line script

- .github/ISSUE_TEMPLATE/1-lts-release-checklist.md
I was the release lead for Jenkins 2.492.1 and I would like to suggest some changes to the checklist based on my experience.
Fixes #647
> Updates and clarifications on release checklist

- profile.d/security
Prepare 2025-04-02 security release based on the canuplin repository
> Prepare 2.492.3 security update

- profile.d/security
Prepare 2025-04-02 security release based on the canuplin repository
> Prepare 2.504 security update

- PodTemplates.d/package-linux.yaml
- PodTemplates.d/release-linux.yaml
Reverts jenkins-infra/release#686
> Revert "Bump `jenkinsciinfra/packaging` Docker image version to 6.0.53"

- .gitignore
- profile.d/stable
1. Added `.DS_Store` to the ".gitignore" file for macOS. 
2. Updated `JENKINS_VERSION` in "profile.d/stable" to `2.504.2`.
> chore(lts): init 2.504.2

- PodTemplates.d/package-linux.yaml
- PodTemplates.d/package-windows.yaml
- PodTemplates.d/release-linux.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4121#issuecomment-2890355054
bump runtime jdk from jdk-17 to jdk-21
> feat!: bump jdk from 17 to 21

- Jenkinsfile.d/core/package
- PodTemplates.d/package-linux.yaml
- utils/release.bash
Ref. https://github.com/jenkins-infra/helpdesk/issues/4774#issuecomment-3204715123
Requires https://github.com/jenkinsci/packaging/pull/529
> chore(packaging) use the new infrastructure NFS volume `data-storage` with preserved timestamp when copying to remote systems

- Jenkinsfile.d/core/package
partial revert of pull request:
* #740
see issue:
* https://github.com/jenkins-infra/helpdesk/issues/4783
> fix(package): use master branch for packaging
