Jenkinsfile.d/package, Jenkinsfile.d/release, PodTemplates.d/package-linux, PodTemplates.d/package-windows
This PR introduce the following changes:
Regarding Packaging:
* We now mount s azure file storage directly inside release.ci.jenkins.io in order to generate package site metadata for debian, redhat and suse when we publish the different artifacts
* We add a new publishing step which call make *.publish for each distribution package
Regarding Release:
* We now run git commit from the jnlp container in order to use the ssh agent
=> Improve Release and Pcakaging process

Jenkinsfile.d/package
make.ps1 has a -War parameter that you can use to specify the war file location. Previously, since you are using `bat` it would require you to use `set WAR <PATH_TO_WAR>` since it is running under cmd.exe (with the bat step) instead of powershell.
=> Use -War parameter

Jenkinsfile.d/release, profile.d/experimental, profile.d/weekly, utils/release.sh
This PR allows to easily use different release profile in order to change following behavior
* Release from a different git repository than jenkinsci/jenkins
* Push generated artifacts on a different maven repository
* Use a different GPG key
=> Move git clone operation from Jenkinsfile to utils/release.sh

Jenkinsfile.d/package, Jenkinsfile.d/release, utils/release.sh
pfx secrets stored on Azure key vault needed to be base64 decrypted and we also need to as password to it
=> Decode base64 pfx certficate from key vault and add a password

Jenkinsfile.d/package, profile.d/experimental, profile.d/stable, utils/release.sh
Move some jenkinsci/packaging variable to profile.d files, so we can have different settings based on release profile.
By calling jenkinsci/packaging scripts from release.sh, it also allows us to reuse environments variables defined in release.sh without having to duplicate same declarations into different locations.
=> release.sh can be used as a wrapper around jenkinsci/packaging Makefile

Jenkinsfile.d/package, utils/release.sh
Environment variables used by packaging script doesn't appear to be correctly exported
=> Export env variable used by packaging script

Jenkinsfile.d/package
This uses the bat file syntax to set the WAR environment variable and uses `%CD%` for the current directory since the `dir` step is used above.
=> Use bat file syntax for setting the environment variable

Jenkinsfile.d/package
- Dump the environment variables prior to calling make.ps1
- Use powershell step instead of bat step that calls powershell.exe
=> Dump environment variables and use powershell step

Jenkinsfile.d/package, profile.d/experimental
In order to work, this pull request requires the credential 'pkgserver' to be configured on release.ci.jenkins.io
=> Add ssh credentials to push artifacts to pkg.jenkins.io then force a mirror sync

utils/release.sh
The first job on release.ci.jenkins.io triggered a weekly release, fortunately enough no production credentials are currently set. Unless we specify a profile by parameter, we shouldn't trigger a release
=> By default don't trigger weekly release

PodTemplates.d/package-linux
This PR aligns with binary location defined from jenkinsci/packaging.
website-core-packages is probably not needed anymore but it can stay there for now
=> Update release environment binary  path

Jenkinsfile.d/package, profile.d/experimental, utils/release.sh
By moving this instruction to release.sh, it allows us to use profile.d, in order to have different behaviors based on profile
=> Move mirror synchronization to release.sh

Jenkinsfile.d/package
In the current state, we archive './msi/build/bin/Release/en-US/jenkins-2.223.msi' so when unarchive it to $MSI, instead of creating the file $WORKSPACE/release/jenkins.msi, it creates $WORKSPACE/release/jenkins.msi/msi/build/bin/Release/en-US/jenkins-2.223.msi 
What we want to have is:
$WORKSPACE/release/jenkins-${VERSION}.msi
=> Don't archive full msi patch, just artifacts

utils/getJenkinsVersion.py, utils/release.sh
Because environment variables are not exported, getJenkins.py use the default value for JENKINS_DOWNLOAD_URL which is downloading jenkins.war from local maven repository
Currently getJenkinsVersion.py is using python 2 and doesn't support basic authentication, I have a fix coming soon
=> Export variables needed for downloadJenkins war file

Jenkinsfile.d/package
Credentials needed to retrieve jenkins.war from private repository
=> Add Maven credentials to Jenkinsfile.d/package

utils/getJenkinsVersion.py
Writing to binary file changed a little bit in python 3
=> Correctly write jenkins.war to binary file

Jenkinsfile.d/package
This shell command is not needed as it was replaced by the next one in order to use environment variables
=> Remove duplicate step

PodTemplates.d/package-linux
The release environment use a different directory between binaries  and pkg.jenkins.io.
=> Update linux pckage pod template to mount website dir in the correct location

Jenkinsfile.d/components/remoting, Jenkinsfile.d/release, README.adoc, profile.d/components/remoting, profile.d/experimental, profile.d/stable, profile.d/weekly, utils/release.sh
This pull request makes it a little bit more generic in order to use scripts in this repository for releasing jenkins components as well.
I was able to test locally all the parts including publishing artifacts on repo.jenkins-ci.org in a private repository.
The only part that I wasn't able to easily reuse are `utils/release.sh --verifyGPGSignature` and `utils/release.sh --verifyCertificateSignature` as we need to know in advance artifact name and at the moment they contain version numbers like `remoting-4.4.jar` vs `remoting.jar` 
In order for this pull request to, we also have to configure maven release plugin on jenkinsci/remoting  as proposed in this [PR](https://github.com/jenkinsci/remoting/pull/381) and obviously also configure release.ci.jenkins.io …
=> [INFRA-2619][WIP] Release component jenkinsci/remoting

PodTemplates.d/package-windows
This label is needed by the jenkins master from release environment [link](https://github.com/jenkins-infra/charts/tree/master/helmfile.d/jenkins-release)
It needs to be jenkins/<helm-release-name>-<agentComponentName>: true
Because this image is packaged with jnlp for windows we don't try to inherit podtemplate settings from jenkins master like we do for linux PodTemplates, maybe we could have a similar approach where our PodTemplate is composed of two containers [jnlp,vstools] @slide? in which case we don't have to specify this label here but instead we just use something similar to [this](https://github.com/jenkins-infra/release/blob/master/Jenkinsfile.d/core/package#L6)
=> Add networkpolicy label to windows template

utils/getJenkinsVersion.py
.metadata.xml
```
<metadata>
<groupId>org.jenkins-ci.main</groupId>
<artifactId>jenkins-war</artifactId>
<versioning>
<latest>2.241</latest>
<release>2.235.1</release>
...
```
versioning/release contains the latest release version in date and not in terms of the version number
=> Weekly "release" must release the latest version available

PodTemplates.d/package-windows
Tested with the command 
```
kubectl run --generator=run-pod/v1  -n release --image=mcr.microsoft.com/dotnet/framework/sdk:3.5 --overrides='{"apiVersion":"v1","spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchFields":[{"key":"metadata.name","operator":"In","values":["akswin000002"]}]}]}}},"tolerations": [{"key": "os","operator":"Equal","value": "windows","effect": "NoSchedule"}]}}
' dotnet -- powershell.exe -Command 'Start-Sleep -s 3600'
```
and the  container is correctly sleeping
=> Override default dotnet process

PodTemplates.d/package-windows
Message error
```
Start-Sleep : Cannot validate argument on parameter 'Seconds'. The 7776000 
argument is greater than the maximum allowed range of 2147483. Supply an 
argument that is less than or equal to 2147483 and then try the command again.
At line:1 char:16
+ Start-Sleep -s 7776000
+                ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Start-Sleep], ParameterBinding 
ValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Power 
Shell.Commands.StartSleepCommand
```
=> Reduce sleeping second for dotnet container

Jenkinsfile.d/components/remoting, Jenkinsfile.d/core/package, Jenkinsfile.d/core/release, Jenkinsfile.d/core/weekly, profile.d/security, utils/release.sh
I propose to display based on parameters what we are going to do for releases and packaging jobs.
And by default we wait for user input to validate if we proceed or not, excepted for weekly releases where we don't wait for validation.
While initially I was thinking to do nice formatting using python + jinja2, I decided to not doing it so we don't introduce a new dependency on a python environment for the release part.  
Release plan looks like
```
+ echo 'Show Release Plan'
Show Release Plan
+ showReleasePlan
+ cat
A new security release will be generated.
This new release will use the git repository: git@github.com:jenkinsci-cert/jenkins.git,
using branch experimental then push commits to the same location.
Artifacts will be pushed to the maven repository named "releases"
located on …
```
=> Release plan

Jenkinsfile.d/core/security, Jenkinsfile.d/core/stable, Jenkinsfile.d/core/weekly
[INFRA-2660](https://issues.jenkins-ci.org/browse/INFRA-2660)
Release build job now trigger jobs based on current branch, this PR works with this [one](https://github.com/jenkins-infra/charts/pull/265).
It allows us to trigger releases using a different branch than the master one
=> [INFRA-2660] core release profile trigger build job based on current branch

utils/release.sh
[jenkinsci/remoting](https://github.com/jenkinsci/remoting) is using this server id to push artifacts, while this url appears to be legacy, I don't really have the time to propose a better solution for now.
PS: This is how I finished the last remoting release [here](https://release.ci.jenkins.io/job/components/job/remoting/job/master/18/console)
=> Add maven.jenkins-ci.org server id

PodTemplates.d/release-linux.yaml
Releasing failed on 'JDK Version: 1.8.0_262'
This image has:
```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)
Maven home: /usr/share/maven
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: /usr/local/openjdk-8/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.76-linuxkit", arch: "amd64", family: "unix"
```
=> Try old version of maven to fix signing issue

Jenkinsfile.d/core/package
We recently had multiple issues with the windows packaging that impacted the release process so I propose to have a flag to easily disable it, and by default it is set to false so we can still retrigger a packaging build afterward
=> Add windows packaging enabled flag for core packaging

profile.d/stable
Prepare stable release profile for release 2.235
Reminder:
* No promotion will be enabled
* Windows packaging will be disabled
Related to [PR#3563](https://github.com/jenkins-infra/jenkins.io/pull/3563)
=> Update stable release profile for stable-2.235

Jenkinsfile.d/core/package
Now that this [PR](https://github.com/jenkinsci/docker-inbound-agent/pull/186) has been merged and a new inbound agent published, building MSI packages works again so it doesn't make sense to disable MSI packaging by default
=> By default build windows package

profile.d/security
As discussed previously, both Maven and Git promotion will be done outside this process.
=> Add 2.235.4 security profile

profile.d/security
As discussed previously, both Maven and Git promotion will be done outside this process.
=> Add 2.252 security profile

README.adoc, utils/release.sh
Today during the lts security release,  we didn't detect that we didn't set RELEASELINE to '-stable'.
As a first iteration, I propose to add RELEASELINE to the plan and display 'weekly' if no RELEASELINE is provided as it is used for weekly releases
=> Display RELEASELINE in the pplan

PodTemplates.d/package-windows
We should use a specific version of the Windows container image. This is the version that has fixes for the password issue.
=> Use specific version of the Windows container

PodTemplates.d/package-linux, PodTemplates.d/package-windows
Release environment is pushing releases on the azure file storage used by get.jenkins.io. We know that this storage is not working correctly at the moment and the error we are facing from release.ci.jenkins.io is 
```
+ rsync --include HEADER.html --include FOOTER.html --exclude '*' --compress --recursive --progress --verbose /tmp/1274/html/ /srv/releases/jenkins/debian/
sending incremental file list
rsync: rename "/srv/releases/jenkins/debian/.HEADER.html.30lzaN" -> "HEADER.html": Permission denied (13)
```
For some reasons the file HEADER.html can't be open while FOOTER.html can, so we are totally disabling this volume until we figure it out.
=> Disabling binary-core-packages volume for packaging

Jenkinsfile.d/core/package, PodTemplates.d/package-linux, PodTemplates.d/package-windows, utils/release.sh
The stable-2.263 branch needs all changes from master.
* Invalidate fastly cache during packaging process
* Parametrized FASTLY_SERVICE_ID
* By default build windows package
* Set deloyAtEnd from maven-deploy-plugin
* Display RELEASELINE in the packaging plan
* Use specific version of the Windows container (#107)
* Hacktoberfest - Update to use master branch
* Disabling binary-core-packages volume for packaging
* Use emptyDir instead
The differences between this branch and master are correct as far as I can tell.  They show that it will use the MAVEN_REPOSITORY_NAME 'releases'.  That is the same maven repository name used for the previous stable releases.  As far as I can tell from reviewing https://repos.jenkins-ci.org/ there is no maven repository name 'releases-stable'.
```
$ git diff …
```
=> Merge master branch changes into stable-2.263

PodTemplates.d/package-linux, PodTemplates.d/package-windows
Once this PR is merged, artifacts will be pushed to the azure file storage  used by get.jenkins.io again but I propose to wait for the coming release to be done to not slow down the process
=> Revert - disable file storage

Jenkinsfile.d/core/stable-rc, README.adoc, profile.d/stable-rc
This PR adds a new profile for the stable candidate releases.
The key elements are:
* maven release will use the "snapshot" repository
* Every distribution packages will be published to get.jenkins.io/<distribution>-stable-rc
* JENKINS_VERSION used for distribution packaging will use the latest Jenkins version from the snaphost repository 
Once merged, we need to configure release.ci to uses "stable-rc" jenkinsfile which is defined [here](https://github.com/jenkins-infra/charts/blob/master/config/default/jenkins-release.yaml)
=> Add stable-rc profile

Jenkinsfile.d/core/stable, Jenkinsfile.d/core/weekly, utils/getJenkinsVersion.py
In this PR #104 , I updated the getJenkinsVersion.py script to retrieve the latest version when JENKINS_VERSION is set to 'latest' instead of 'weekly', unfortunately, I forgot to update the  weekly packaging job with JENKINS_VERSION set to latest. 
This PR also includes minor fixes
-> stable packaging job doesn't set JENKINS_VERSION as it shouldn't be configured there but instead in the profile file
-> `utils/getJenkinsVersion.py` doesn't print error message, if it detect a bad version pattern, instead it just skip it
=> Fix weekly packaging job

utils/release.bash
Based on the discussion we had yesterday, I propose following fixes
**Move variable PROMOTE_STAGING_MAVEN_ARTIFACTS_ARGS**
It didn't make sense to set up that variable in every situation considering that it's only use in one place in one scenario of the packaging
**Correctly double-quotes variables**
**Split when calling command from variable substitution**[
doc](https://tldp.org/LDP/abs/html/parameter-substitution.html)
set -e doesn't work in command substitution like `:${VARIABLE:=$(false)}`, instead I first default `DEFAULT_VARIABLE="$(false)"` then do `:${VARIABLE:=$DEFAULT_VARIABLE}` so we can catch errors early
**Correctly convert variable to array**
**Correctly exit in case of errors**
While I tested the following modification manually, I can't guarantee the result on release.ci …
=> Fix various shellcheck errors

utils/release.bash
Match the pattern used elsewhere in the file.  When converting a string variable to an array, use '$' to expand the variable.
=> Expand variable before read converts it to array

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
After the release has been delivered, we need to remove the lts-candidate label from those issues that were included in the release and had been marked as lts-candidate.
=> Extend checklist item to include lts-candidate label removal

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Please delete the branch after merge.  Created on the official repository for my convenience, but don't need the branch once the change is merged.
=> Link to the lts-candidate Jira filter

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md, README.adoc, utils/release.bash
Since the master branch is used for weekly releases, it is good to reduce the differences between the master branch and the stable branch.
- Fix shellcheck errors
- Update utils/release.bash
- Expand variable before read converts it to array
- Improve security documentation
- Extend checklist item to include lts-candidate label removal (#146)
- Link to the lts-candidate Jira filter (#147)
- Fix broken link in release checklist
- Name scripts in the checklist (#152)
=> Merge master changes to stable-2.289

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md, PodTemplates.d/package-windows
This PR merges back to stable-2.289 the 4 last changes from the principal branch.
It includes:
* Windows Packaging fixes: 2 commits, https://github.com/jenkins-infra/release/commit/2d1f11145a1490e116f323fa7fdd19877e6917bc and https://github.com/jenkins-infra/release/commit/92dde3d7af5f869a31644a0ea65d27fe0333eacd around the Windows pod templates for agents in charge of the Windows packaging
*  Add init-lts-line script reference (#162) 
*  Fix RC build instructions (#161)
=> chore: merges latest changes back to stable-2.289

PodTemplates.d/package-windows
It sounds like that we are mounting volume in the windows pod that are not used by the packaging steps.
As this mounts are creating a lot of pressure on the scheduler, let's remove it.
=> Fix: remove volume mounts from Windows Pod template

PodTemplates.d/package-linux, PodTemplates.d/release-linux.yaml
```shell
➜ docker pull microsoft/azure-cli:2.0.59
Error response from daemon: pull access denied for microsoft/azure-cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
➜ docker pull mcr.microsoft.com/azure-cli:2.0.59
2.0.59: Pulling from azure-cli
ff3a5c916c92: Already exists 
471170bb1257: Already exists 
d487cc70216e: Already exists 
9358b3ca3321: Already exists 
d4d73eb5841d: Already exists 
da1be03b2fb6: Pull complete 
4a8b316e2b85: Pull complete 
551cee3868ea: Pull complete 
1d46de139b47: Pull complete 
95bb479797b2: Pull complete 
564dbcb5ac84: Pull complete 
Digest: sha256:86a74ce97b1c37798400847dba8e135adb016068fc4d758cc3d80c90e7a6bf5a
Status: Downloaded newer image for mcr.microsoft.com/azure-cli:2.0.59 …
```
=> Fix: switch microsoft Docker images to their new registry name

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Noted during the release of 2.289.3 that we need the stable-2.289 branch in the release repository to include the latest fixes from the master branch.
=> Check release & packaging branch before build

Jenkinsfile.d/core/package
The packaging build history consumes the majority of the space in the release.ci.jenkins.io Jenkins home directory.  Retain the most recent 15 builds on the master branch in case we need to refer to history, but don't retain anything beyond that.
Does not change the retention of logs from the release build job, just the release packaging job.  Does not change the retention of logs on any of the other packaging branches.
Space use for the master branch packaging history is 10x more than the space use of any other job on the system.
=> Retain history of 15 packaging builds

profile.d/components/remoting
Implementing https://github.com/jenkinsci/remoting/pull/489#issuecomment-978426556, point to https://github.com/jenkinsci/remoting/tree/v4.11.x to get 4.11.2.
=> Update branch for 4.11.2 release

Jenkinsfile.d/core/package, Jenkinsfile.d/core/release
https://github.blog/changelog/2022-04-25-git-io-deprecation/
=> chore: replace git.io link

PodTemplates.d/package-windows.yaml, PodTemplates.d/release-linux.yaml
- https://github.com/jenkins-infra/docker-packaging/pull/36 removed JDK8 and changed the `JAVA_HOME` value
- #237 and #232 changed the Docker image but we forgot to update the pod config
This PR also bumps the package windowsagent remoting version to use recent ones
=> fix(release) Rely on the Docker image `PATH` to locate the default `java` binary

utils/release.bash
See also https://github.com/jenkinsci/packaging/pull/309. This PR adds the `-V` argument when invoking Maven, which displays the version of Maven and Java used in the build without stopping the build, which could be useful for debugging purposes (especially as we switch builds to Java 11).
=> Display Maven version information without stopping build

Jenkinsfile.d/core/package, Jenkinsfile.d/core/release, Jenkinsfile.d/core/stable, Jenkinsfile.d/core/stable-rc, Jenkinsfile.d/core/weekly
Closes https://github.com/jenkins-infra/helpdesk/issues/2979
Using `label` in the `agent {}` section in a Jenkinsfile only make sense for `node`, `docker` or `dockerfile` , as per https://www.jenkins.io/doc/book/pipeline/syntax/#common-options.
=> chore(Jenkinsfiles) remove deprecated label directive for kubernetes agent definitions

PodTemplates.d/package-linux.yaml, PodTemplates.d/release-linux.yaml, utils/release.bash
- https://github.com/jenkins-infra/docker-packaging/compare/2.1.9...2.1.32
- Using the latest image as posible to benefits from @basil 's work on the systemd macros: is this LTS the correct target?
- Reverted the openssl command (related to Ubuntu 22.04) change
- Reverted the java bin path for spawning the inbound agent
```shell
$ docker run --rm -ti --entrypoint=openssl jenkinsciinfra/packaging:2.1.32 pkcs12 --help 2>&1 | grep legacy
$ docker run --rm -ti --entrypoint=openssl jenkinsciinfra/packaging:2.1.41 pkcs12 --help 2>&1 | grep legacy
-legacy             Use legacy encryption: 3DES_CBC for keys, RC2_CBC for certs
$ docker run --rm -ti --entrypoint=/opt/jdk-11/bin/java jenkinsciinfra/packaging:2.1.32 -version                        
openjdk version "11.0.13" 2021-10-19
OpenJDK …
```
=> Revert Ubuntu 22.04/ JDK8-removal changes for stable 2.332

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
As we (infra team) missed the LTS release event today (sorry), WDYT of adding a task to announce the release process start in IRC channels the day it occurs?
=> chore(checklist): add "announce on IRC" task

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Thanks to jetersen, this is now covered by updatecli.
=> docs: Remove JCasC PR for point releases

utils/release.bash
If you have access to it, take a look at e.g. https://release.ci.jenkins.io/job/core/job/release/job/master/169/consoleFull and search for `maven-deploy-plugin`. `maven-deploy-plugin` is not invoked at the end but rather sequentially within each module, indicating the passed-in option is clearly not taking effect. As such it is dead code, and dead code is generally a maintenance burden.
The `release:stage` and/or `release:perform` invocations don't run the deploy task directly, but rather they fork a new copy of Maven in the `run-perform-goals` stage. That copy of Maven gets its arguments from whatever is passed to `-Darguments` in the main Maven process, which does not include `-DdeployAtEnd=true`. As such the `-DdeployAtEnd=true` only applies to a parent process that never invokes the …
=> Remove dead code for `-DdeployAtEnd=true`

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Jenkins 2.277.x is an older release.  Use Jenkins 2.361.x in the examples and reference URLs of the checklist so that it is clear that the checklist is being maintained and regularly reviewed.
=> Use recent release as example in checklist template

Jenkinsfile.d/core/package, Jenkinsfile.d/core/release, Jenkinsfile.d/core/stable, Jenkinsfile.d/core/stable-rc, Jenkinsfile.d/core/weekly
Closes https://github.com/jenkins-infra/helpdesk/issues/2925
This PR introduces 2 min changes:
- Stop allocating a node for the "top-level" job: it will run in a "ligthweight executor" (e.g. a JVM thread) in the controller which is expected to survive controller restart. Less moving pieces, less code, less resource usage.
- Enable the "retry" top-level directive thanks to @jglick's recent work. This directive ensures that in most usual cases (sush as a controller restart), the pipeline shoud *resume*. Tested manually: if the `sh` step was started, then it continues the pipeline when resuming.
- There are still some edge cases where the pipeline does not resume: if the pipeline instruction is not durable.
=> fix(Jenkins Pipelines) do not allocate agent for "parent" pipelines and retry the packaging process a 2nd time

profile.d/stable
Create or update release branch in [jenkins-infra/release](https://github.com/jenkins-infra/release), e.g. stable-2.361:
=> Feat: Init 2.361.2

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md, .github/ISSUE_TEMPLATE/config.yml
IRC channels are now bridged to matrix, which is bridged to gitter.
Benefits are, that it's easier to access, without the need to set up a bouncer to stay connected or read past messages, unless you are already using matrix.
=> Replace IRC with bridged channels

utils/release.bash
Fixes a regression exposed by jenkinsci/pom#281 and jenkinsci/jenkins#6914. In order for release artifacts to be signed by `maven-gpg-plugin` and `maven-jarsigner-plugin` during the `release:prepare` goal, we rely on https://github.com/jenkinsci/jenkins/blob/d25704cfbc929bca3bd5e5675e1fe1aa1a58928c/pom.xml#L521-L540 and https://github.com/jenkinsci/jenkins/blob/d25704cfbc929bca3bd5e5675e1fe1aa1a58928c/war/pom.xml#L623-L648, activated by the `release` and `sign` profiles respectively. To activate these profiles during the `release:prepare` goal we currently rely on https://github.com/jenkinsci/jenkins/blob/d25704cfbc929bca3bd5e5675e1fe1aa1a58928c/pom.xml#L428-L429, which happens to expose a serious bug in recent versions of Maven Release Plugin as explained in …
=> Add `sign` to `<activeProfiles>`

README.adoc, utils/release.bash
The release build sets `-Darguments` in various places in a futile attempt to reduce log spam, futile because that setting is ignored due to the presence of https://github.com/jenkinsci/jenkins/blob/d25704cfbc929bca3bd5e5675e1fe1aa1a58928c/pom.xml#L429, as one can see by looking at the actual console output and seeing the log spam. And furthermore, the presence of custom arguments anywhere (either via `-Darguments` in the top-level Maven invocation or in the `maven-release-plugin` configuration in `pom.xml`) seems to break the `release:stage` goal in Maven Release Plugin 3.x as described in https://github.com/jenkins-infra/helpdesk/issues/3143#issuecomment-1254040470, so removing this dead code takes us one step closer toward working around the problem (the other step being removing the …
=> Remove dead arguments code

utils/release.bash
Ref. https://github.com/jenkins-infra/helpdesk/issues/3143. (line edited at this PR does not fix any problem).
It ensures that the specified staging repository uses the new maven-deploy layout as per https://maven.apache.org/plugins/maven-deploy-plugin/#major-version-upgrade-to-version-3-0-0.
In order to merge PR, I need help by Maven expert to confirm that I'm not doing something crazy here.
Ping @basil @jglick @jnord @daniel-beck @timja @MarkEWaite you are my Maven experts 🍯 May I get your advise?
=> fix(release script) use the new staging repository layout maven when staging a release

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Content on the master branch should go through the same backporting process, like any other changes that land on stable branches.
If there's no change, that's eligible for a backport, the branches should not be merged.
=> Remove master branch merges from LTS template

updatecli/updatecli.d/docker-packaging.yml
Besides fixing deprecated directive, it also adds the "version" of the image in PR titles (nicer)
=> chore(updatecli) cleanup manifests for v0.38.0

profile.d/stable
Create or update release branch in [jenkins-infra/release](https://github.com/jenkins-infra/release), e.g. stable-2.375:
=> Feat: Init 2.375.2

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Since yesterday, February the 13th, Gitter migrated to matrix. Existing links are redirected, but some redirections broke or use a different URL.
This PR updates the link to use the final destination, to ensure we don't rely on possible breaking redirections.
=> Gitter url

.github/workflows/updatecli.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402
=> chore: pin GitHub actions with their SHA-1 instead of their version number

Jenkinsfile.d/core/weekly
Reverts jenkins-infra/release#336
Do not merge before the 8th of March 2023, cf https://github.com/jenkins-infra/helpdesk/issues/3428
=> Revert "Disable weekly build temporarily"

Jenkinsfile.d/components/remoting, Jenkinsfile.d/core/release
Thanks @jglick for the suggestion in https://github.com/jenkins-infra/pipeline-library/issues/523#issuecomment-1323906482
Fixes https://github.com/jenkins-infra/release/issues/313
=> chore: replace `readProperties` by a shell script

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
1. Update broken `release guide` link using absolute path instead of relative path as the latter is broken after issue is opened using this template.
2. Update example version from LTS 2.361 to 2.387. 
3. Add missing punctuations and make minor grammatical editings.
=> Update LTS Release Checklist template

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/2234
=> Remove jcasc from LTS release template (as moving to bom)

PodTemplates.d/package-linux.yaml, PodTemplates.d/package-windows.yaml, PodTemplates.d/release-linux.yaml
This PR adapts the pod templates to the privatek8s nodes defined here: https://github.com/jenkins-infra/azure/blob/62f0ff898ec69ffe677fd7c37e3fc366f5b3e318/privatek8s.tf#L101-L138
In draft until the final phase of the release.ci.jenkins.io migration from prodpublick8s to priatek8s cluster is started.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2844
=> chore: adapt pod templates to `privatek8s` nodes taints

Jenkinsfile.d/core/package
Windows MSI packaging needs a code signing certificate.  Our code signing certificate has expired.  Attorneys from Linux Foundation and Continuous Delivery Foundation are working to resolve the issues.  Don't publish an MSI until the code signing certificate is again available.
Matching pull request in the packaging repository:
* https://github.com/jenkinsci/packaging/pull/384
=> Do not publish MSI

Jenkinsfile.d/components/remoting, Jenkinsfile.d/core/package, Jenkinsfile.d/core/release
Related to https://github.com/jenkins-infra/helpdesk/issues/3323
Blocked by https://github.com/jenkins-infra/kubernetes-management/pull/3789
This PR follows up https://github.com/jenkins-infra/release/pull/357 and https://github.com/jenkinsci/packaging/pull/385 which enable MSI generation again.
The goal is to ensure the new Digicert cert is used to sign the MSI (and the JAR).
Please note that we also are explicitly using a year on the GPG passphrase changed last week, for homogeneity
=> feat: ensure that new 2023 digicert is used + GPG 2023 passphrase

Jenkinsfile.d/components/remoting, Jenkinsfile.d/core/package, Jenkinsfile.d/core/release
- feat: use the new 2023 digicert - helpdesk-3323
- fix: ensure the GPG passphrase is rotated for 2023
https://github.com/jenkins-infra/release/pull/358 applied to the
stable-2.387 branch
=> Update stable-2.387 code signing configuration

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md, README.adoc, docs/releases.md
BO is in a maintenance-only state for almost a couple of years. I'd like to remove our reliance on BO URLs here, given the branches and jobs are well accessible through the native UI too.
=> Drop reliance on BO URLs

Jenkinsfile.d/components/remoting
Corresponding issue: https://github.com/jenkins-infra/release/issues/313
Ref: https://github.com/jenkins-infra/pipeline-library/issues/523#issuecomment-1472187331
=> chore: backport of #339 on `stable-2.375` to replace `readProperties` by a shell script

Jenkinsfile.d/components/remoting
Corresponding issue: https://github.com/jenkins-infra/release/issues/313
Ref: https://github.com/jenkins-infra/pipeline-library/issues/523#issuecomment-1472187331
=> chore: backport of #339 on `stable-2.387` to replace `readProperties` by a shell script

profile.d/stable
Updated `JENKINS_VERSION` values in the environment file (`profile.d/stable`) to match the release.
=> Init LTS 2.401.3

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md, docs/releases.md
Depends on https://github.com/jenkinsci/jenkins/pull/8282
I thought we can automate this process, given it's based on a template, essentially.
Preview from my demo repository:
=> Revise RC announcement part

tools/init-lts-line
The script in question has been removed, and the calendar is (typically) filled with dates in advance, nor does it seem that all members of the release team https://github.com/orgs/jenkins-infra/teams/release have access to it, at least, I don't.
=> Revise post LTS line creation steps

PodTemplates.d/package-linux.yaml, PodTemplates.d/package-windows.yaml, PodTemplates.d/release-linux.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3072
This PR ensures that https://github.com/jenkins-infra/docker-packaging/pull/75 (released as https://github.com/jenkins-infra/docker-packaging/releases/tag/4.0.0) is deployed.
It also ensures that Windows packaging pod agent is using JDK17 (agent process).
=> Bump pod agent images to use JDK17 for agent processes but keep JDK11 for building Jenkins

PodTemplates.d/package-windows.yaml
The `JENKINS_JAVA_OPTS` variable caused errors during the `2.410` and `2.414.1` releases by failing the Windows pod allocation with a JVM flag error.
As per https://github.com/jenkinsci/docker-inbound-agent#windows-jenkins-java-opts, the double quote `"` is required for this flag
Tested with a replay: it works and the resulting value in the pod template for the environment variable is `value: "\"-XX:+PrintCommandLineFlags\" --show-version"`
(edit)
Proposal: 
- This PR is not urgent: we have until the 28 so it will be used for the 2.421 weekly
- If it works properly for the 2.421, then we'll cherry pick to `stable-2.414` (it works currently on this branch so not mandatory but nice to have except it must NOT break next time: I already broke too much things here)
=> fix(package-windows) revert additional environment variables for `jnlp` container

profile.d/stable
Modified the `JENKINS_VERSION` value in the environment file (profile.d/stable) to match the release.
=> Modify the JENKINS_VERSION value in profile.d/stable

profile.d/security
Reverts jenkins-infra/release#435
These PRs target their own temporary branches per https://github.com/jenkins-infra/release#security (step 1)
=> Revert "Prepare security 2.424"

profile.d/stable
Modified the `JENKINS_VERSION` value in the environment file (profile.d/stable) to match the new point release.
=> Init LTS 2.414.3

tools/lts-candidate-stats
A [stackoverflow article](https://stackoverflow.com/questions/55169114/unable-to-add-xmlslurper-to-eclipse-groovy-project) suggests widening the import.  That worked for me on Red Hat Enterprise Linux 8 with groovy 2.4.21 installed using sdkman.
No problem if this is not accepted, since I haven't tested it on any other distribution.  I needed it in my environment and can keep it on a private branch.
=> Widen groovy import in lts-candidate-stats script

profile.d/stable
Updated the JENKINS_VERSION in profile.d/stable to init LTS 2.462.2 release.
=> Init LTS 2.426.2 release

utils/release.bash
Fixes https://github.com/jenkins-infra/release/issues/387
Intentionally limited to only push if using the weekly release profile because we do not expect to receive commits during a build on a branch that is not a weekly build.  LTS builds and security builds that have a commit arrive during the build should continue to fail the build.
Confirmed that `git fetch origin` and `git merge --no-edit origin/master` do not create a merge commit when there is nothing to merge or when the merge is a fast forward merge.
Confirmed that `git fetch origin` and `git merge --no-edit origin/master` create a merge commit when there is a local commit.
Confirmed on release.ci.jenkins.io that `RELEASE_PROFILE` is defined for weekly releases (like 2.439) as 'weekly' and that `RELEASE_PROFILE` is defined for …
=> Allow weekly build to merge before push

utils/release.bash
No benefit to retaining unused command line arguments.
Fixes https://github.com/jenkins-infra/release/issues/488
=> Remove the unused --rollback argument

profile.d/stable
Updated `JENKINS_VERSION` to `2.440.3` in the environment file (`profile.d/stable`).
=> Feat: Init LTS 2.440.3

profile.d/stable
Updated `JENKINS_VERSION` in "profile.d/stable" to init LTS 2.452.2.
=> chore: init lts 2.452.2

profile.d/stable
Updated `JENKINS_VERSION` in "profile.d/stable".
=> chore: init LTS 2.452.3 release

tools/init-lts-line, utils/release.bash
The `sed -i ""` syntax works on the BSD variants but not on Linux variants.
The `sed -i` syntax works on Linux variants but not on BSD variants (like macOS).
The `sed -i''` syntax works on both BSD variants and Linux variants.
=> Fix sed for Linux

profile.d/stable
Modified the `JENKINS_VERSION` value in the environment file (`profile.d/stable`) to match the release.
=> Init stable 2.462 LTS

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Release created by Kris Stern did not run the GitHub action to post the notifications.  Release created by Mark Waite did.  Not clear why, but assume there differences in permissions.
=> If automatic announce fails, send the usual way

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
Follow the same pattern in the future as was suggested by Daniel Beck in the [Jenkins developer mailing list message](https://groups.google.com/g/jenkinsci-dev/c/ca7Lp0x6Kqs/m/QwHj66hZAgAJ).
=> Add LTS baseline selection comment for security releases

docs/releases.md
Also adds a link to previous pull requests for the BOM update.
=> Update the pre-requisites - Java 17 or 21 and Maven 3.9.6 or newer

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md
The packaging job defines parameters in the Jenkinsfile.  That means the first run of the packaging job ignores the values of those parameters that are passed from the job that launches the packaging job.
Include a checklist item to remind the release lead.
=> Add checklist item to run and cancel new packaging job

profile.d/stable
To update `JENKINS_VERSION` value in `profile.d/stable` to init 2.479.2 LTS.
=> chore: init 2.479.2 lts

Jenkinsfile.d/core/weekly
During the end of year break, we won't have Jenkins infrastructure team members generally available.  Rather than risk needing to escalate a broken weekly build to one of them while they are out of office, let's pause weekly builds.
Proposed and discussed in [Jenkins developer mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/YcuXoxF44ko/m/Rp11aa9fAQAJ).
Confirmed in Jenkins infrastructure team meeting 17 Dec 2024.
=> Disable weekly build for end of year break

Jenkinsfile.d/core/weekly
Reverts jenkins-infra/release#634
Now we've passed the 2 weeks break and we are in 2025, we want to weekly release to happen next Tuesday.
=> Revert "Disable weekly build for end of year break"

.gitignore, profile.d/stable
1. Updated `JENKINS_VERSION` to `2.492.2` in profile.d/stable to initiate LTS release
2. Added `.DS_Store` to `.gitignore` for local development environment in macOS
=> chore: init 2.492.2 lts release

Jenkinsfile.d/core/weekly
As usual before a security update, disable the regular Tuesday weekly build.
=> Disable weekly build

Jenkinsfile.d/core/weekly
We're done with the security release, I'm reverting https://github.com/jenkins-infra/release/pull/659
=> Revert 'Disable weekly build'

profile.d/stable
Updated `JENKINS_VERSION` to `2.492.3` in profile.d/stable to initiate LTS release.
=> chore: init 2.492.3 lts release

profile.d/stable
- **chore(stable): bump Jenkins version to 2.504.3**
=> Stable 2.504.3

PodTemplates.d/package-linux.yaml, PodTemplates.d/package-windows.yaml, PodTemplates.d/release-linux.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4696#issuecomment-3008168249
lets enable workload identity for the MASTER branch pods for now
=> feat(PodTemplates): adding service account spec for workload identity usage

.github/ISSUE_TEMPLATE/1-lts-release-checklist.md, docs/releases.md, tools/README.md, tools/list-issue-commits.sh
Fixes https://github.com/jenkins-infra/release/issues/409
Recalculating via epoch makes it work without using `date`, given it's a bit weird on macOS, and I would rather not start messing with `gdate`.
Additionally, I've changed the wording, as I found it a bit difficult to match the task of the script. The output on my macOS is as follows (the Jira issue is present on multiple commits on the master branch, bad merge?): The commit is visible on the master branch only.
```
./a.sh JENKINS-73161
jenkins-2.530 (0 days) 349d4fc407 [JENKINS-73161] Ensure file parameters are retained across Jenkins restarts (#11081)
jenkins-2.530 (0 days) d01cedafa3 [JENKINS-73161] Ensure file parameters are retained across Jenkins restarts
Unique commits on master branch: 349d4fc407 d01cedafa3
Commits present …
```
=> Make 'list-issue-commits' platform agnostic
